# create a action file that runs yarn install then yarn deploy. After that, upload release-extension.7z to releases tab based on github actions

name: Release Extension

on:
  push:
    branches:
      - master

jobs:
    build-extension:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16
        - name: Install Yarn
          run: npm install -g yarn
        - name: Install Dependencies
          run: yarn install
        - name: Build Extension
          run: yarn deploy
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: |
              release-extension.7z
              LICENSE
              dist/info.json
            tag_name: Release-${{ github.ref }}
            body: |
              Just install in vortex and enjoy!
            draft: false
            prerelease: false
            token: ${{ secrets.GITHUB_TOKEN }}
                      
      

